# Generated by Django 5.1.7 on 2025-08-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('Seccap_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=20)),
                ('choice_of_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamps', models.DateTimeField()),
                ('status_of_attendance', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.student_data')),
            ],
        ),
    ]
