# Generated by Django 5.1.7 on 2025-08-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0002_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendance',
            old_name='student',
            new_name='student_id',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
