# Generated by Django 5.1.7 on 2025-08-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0003_rename_student_student_attendance_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_attendance',
            old_name='student_id',
            new_name='seccap_object_foreign_key',
        ),
    ]
