# Generated by Django 5.1.7 on 2025-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0004_rename_student_id_student_attendance_seccap_object_foreign_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Attendance',
        ),
    ]
