# Generated by Django 5.1.7 on 2025-08-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0005_delete_student_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_attendance', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('time_stamps', models.DateTimeField()),
                ('seccap_object_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.student_data')),
            ],
        ),
    ]
